# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Page1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(990, 141)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Scan_button = QtWidgets.QPushButton(self.centralwidget)
        self.Scan_button.setGeometry(QtCore.QRect(50, 40, 81, 71))
        self.Scan_button.setObjectName("Scan_button")
        self.Start_button = QtWidgets.QPushButton(self.centralwidget)
        self.Start_button.setGeometry(QtCore.QRect(130, 40, 81, 71))
        self.Start_button.setObjectName("Start_button")
        self.Stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.Stop_button.setGeometry(QtCore.QRect(210, 40, 81, 71))
        self.Stop_button.setObjectName("Stop_button")
        self.Manual_button = QtWidgets.QPushButton(self.centralwidget)
        self.Manual_button.setGeometry(QtCore.QRect(290, 40, 81, 71))
        self.Manual_button.setObjectName("Manual_button")
        self.Settings_button = QtWidgets.QPushButton(self.centralwidget)
        self.Settings_button.setGeometry(QtCore.QRect(370, 40, 81, 71))
        self.Settings_button.setObjectName("Settings_button")
        self.Unique_code_button = QtWidgets.QPushButton(self.centralwidget)
        self.Unique_code_button.setGeometry(QtCore.QRect(450, 40, 101, 71))
        self.Unique_code_button.setObjectName("Unique_code_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 10, 55, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 10, 55, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 10, 55, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 10, 61, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(380, 10, 71, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(460, 10, 91, 31))
        self.label_6.setObjectName("label_6")
        self.Text_Area = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Text_Area.setGeometry(QtCore.QRect(570, 20, 281, 87))
        self.Text_Area.setLineWidth(1)
        self.Text_Area.setObjectName("Text_Area")
        self.Quit_button = QtWidgets.QPushButton(self.centralwidget)
        self.Quit_button.setGeometry(QtCore.QRect(890, 40, 81, 71))
        self.Quit_button.setObjectName("Quit_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sonion Laser"))
        self.Scan_button.setText(_translate("MainWindow", "Scan"))
        self.Start_button.setText(_translate("MainWindow", "START"))
        self.Stop_button.setText(_translate("MainWindow", "STOP"))
        self.Manual_button.setText(_translate("MainWindow", "MANUAL"))
        self.Settings_button.setText(_translate("MainWindow", "SETTINGS"))
        self.Unique_code_button.setText(_translate("MainWindow", "UNIQUE CODE"))
        self.label.setText(_translate("MainWindow", "SCAN"))
        self.label_2.setText(_translate("MainWindow", "START"))
        self.label_3.setText(_translate("MainWindow", "STOP"))
        self.label_4.setText(_translate("MainWindow", "MANUAL"))
        self.label_5.setText(_translate("MainWindow", "SETTINGS"))
        self.label_6.setText(_translate("MainWindow", "UNQUE CODE"))
        self.Quit_button.setText(_translate("MainWindow", "QUIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
