# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Printer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Printer(object):
    def setupUi(self, Printer):
        Printer.setObjectName("Printer")
        Printer.resize(681, 818)
        self.centralwidget = QtWidgets.QWidget(Printer)
        self.centralwidget.setObjectName("centralwidget")
        self.TEXTBOX_SN = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.TEXTBOX_SN.setGeometry(QtCore.QRect(20, 30, 75, 758))
        self.TEXTBOX_SN.setObjectName("TEXTBOX_SN")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 55, 16))
        self.label.setObjectName("label")
        self.TEXTBOX_Bar = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.TEXTBOX_Bar.setGeometry(QtCore.QRect(120, 30, 113, 758))
        self.TEXTBOX_Bar.setObjectName("TEXTBOX_Bar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 10, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 10, 55, 16))
        self.label_3.setObjectName("label_3")
        self.TEXTBOX_Bar_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.TEXTBOX_Bar_2.setGeometry(QtCore.QRect(260, 30, 113, 758))
        self.TEXTBOX_Bar_2.setObjectName("TEXTBOX_Bar_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(430, 10, 55, 16))
        self.label_4.setObjectName("label_4")
        self.TEXTBOX_Bar_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.TEXTBOX_Bar_3.setGeometry(QtCore.QRect(400, 30, 113, 758))
        self.TEXTBOX_Bar_3.setObjectName("TEXTBOX_Bar_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(570, 10, 55, 16))
        self.label_5.setObjectName("label_5")
        self.TEXTBOX_Bar_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.TEXTBOX_Bar_4.setGeometry(QtCore.QRect(540, 30, 113, 758))
        self.TEXTBOX_Bar_4.setObjectName("TEXTBOX_Bar_4")
        Printer.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Printer)
        self.statusbar.setObjectName("statusbar")
        Printer.setStatusBar(self.statusbar)

        self.retranslateUi(Printer)
        QtCore.QMetaObject.connectSlotsByName(Printer)

    def retranslateUi(self, Printer):
        _translate = QtCore.QCoreApplication.translate
        Printer.setWindowTitle(_translate("Printer", "Printer"))
        self.label.setText(_translate("Printer", "Serial"))
        self.label_2.setText(_translate("Printer", "Barcode"))
        self.label_3.setText(_translate("Printer", "Barcode"))
        self.label_4.setText(_translate("Printer", "Barcode"))
        self.label_5.setText(_translate("Printer", "Barcode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Printer = QtWidgets.QMainWindow()
    ui = Ui_Printer()
    ui.setupUi(Printer)
    Printer.show()
    sys.exit(app.exec_())
