# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UniqueUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectUniqueCode(object):
    def setupUi(self, SelectUniqueCode):
        SelectUniqueCode.setObjectName("SelectUniqueCode")
        SelectUniqueCode.resize(338, 426)
        self.centralwidget = QtWidgets.QWidget(SelectUniqueCode)
        self.centralwidget.setObjectName("centralwidget")
        self.SU60left_button = QtWidgets.QPushButton(self.centralwidget)
        self.SU60left_button.setGeometry(QtCore.QRect(40, 50, 101, 61))
        self.SU60left_button.setObjectName("SU60left_button")
        self.SU60right_button = QtWidgets.QPushButton(self.centralwidget)
        self.SU60right_button.setGeometry(QtCore.QRect(190, 50, 101, 61))
        self.SU60right_button.setObjectName("SU60right_button")
        self.SU85left_button = QtWidgets.QPushButton(self.centralwidget)
        self.SU85left_button.setGeometry(QtCore.QRect(40, 140, 101, 61))
        self.SU85left_button.setObjectName("SU85left_button")
        self.SU85right_button = QtWidgets.QPushButton(self.centralwidget)
        self.SU85right_button.setGeometry(QtCore.QRect(190, 140, 101, 61))
        self.SU85right_button.setObjectName("SU85right_button")
        self.SU100left_button = QtWidgets.QPushButton(self.centralwidget)
        self.SU100left_button.setGeometry(QtCore.QRect(40, 230, 101, 61))
        self.SU100left_button.setObjectName("SU100left_button")
        self.SU100right_button = QtWidgets.QPushButton(self.centralwidget)
        self.SU100right_button.setGeometry(QtCore.QRect(190, 230, 101, 61))
        self.SU100right_button.setObjectName("SU100right_button")
        self.MSPM_button = QtWidgets.QPushButton(self.centralwidget)
        self.MSPM_button.setGeometry(QtCore.QRect(120, 310, 101, 61))
        self.MSPM_button.setObjectName("MSPM_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        SelectUniqueCode.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SelectUniqueCode)
        self.statusbar.setObjectName("statusbar")
        SelectUniqueCode.setStatusBar(self.statusbar)

        self.retranslateUi(SelectUniqueCode)
        QtCore.QMetaObject.connectSlotsByName(SelectUniqueCode)

    def retranslateUi(self, SelectUniqueCode):
        _translate = QtCore.QCoreApplication.translate
        SelectUniqueCode.setWindowTitle(_translate("SelectUniqueCode", "Select Unique Code"))
        self.SU60left_button.setText(_translate("SelectUniqueCode", "SU60 LEFT"))
        self.SU60right_button.setText(_translate("SelectUniqueCode", "SU60 RIGHT"))
        self.SU85left_button.setText(_translate("SelectUniqueCode", "SU85 LEFT"))
        self.SU85right_button.setText(_translate("SelectUniqueCode", "SU85 RIGHT"))
        self.SU100left_button.setText(_translate("SelectUniqueCode", "SU100 LEFT"))
        self.SU100right_button.setText(_translate("SelectUniqueCode", "SU100 RIGHT"))
        self.MSPM_button.setText(_translate("SelectUniqueCode", "MS PM"))
        self.label.setText(_translate("SelectUniqueCode", "GAMMA SU"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SelectUniqueCode = QtWidgets.QMainWindow()
    ui = Ui_SelectUniqueCode()
    ui.setupUi(SelectUniqueCode)
    SelectUniqueCode.show()
    sys.exit(app.exec_())
